spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epilog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Jnbivcb7@@12
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  logging:
    level:
      org.hibernate.SQL: debug
  servlet:
    multipart:
      max-file-size: 200MB

jwt:
  expiration_time: 86400000 #1일
  secret: H/BefKpJWtc3gBYcpI7DgXxtPPdDWYOoGbW/Y8bmOUE=

sms:
  cool:
    api: NCSJQ6WTVMJRXQER
    secret: JW3IK236UH9QUXHJEXVEHNXNPWBZC10V
  map:
    api: AIzaSyDiFV0KoQm4Hzfmwyw9MQAZELr1O5gQUoc

kakao:
  api:
    key: 67dc1dd91122c3760d26ce19ef697dfd

bitly:
  api:
    token: f812aecd0509974b90ef2c276017d269f317bb4b

firebase:
  json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGlhbG9nLTI1ZjM3IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiY2ZjMjdkOGYwNzEyMjkwYjk4YTNjNWM3NjdhODZhMjYwMmUzZWYwYiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFENXV0akRQNzdMRnNlWFxuSXZzNS9BTy9lTHFoT2VjemtEakpHQS9uK0UzbldRQmc0VzVIOWtDUHFhMldELzRzMU5QUW5vWUdIRDI1TERzblxuSForcjBjQnd5WXNLN2kvWWNROVVibHJ2MmhSMlZHRGRtcFF6NHZkaTZRcVRjcGJzM2lQQUY3Z1hvMStKWEN5blxuL1FIcVBuWjVja2dBbFk5ajFHSGJKbHZHOFQ1czNNSC83aWw0SFVSdVA2T1BPbEJzVk5DVjFFbTF1OW8wb29QNlxuRDExYkloeWFPZ3JVNklvS3VCL0xScGwzTEo5aEd1UXF6bDNmVzlJRjlnbDZhUjdNMXE4T2lhcTRKOEVDS3YzelxuUEFMOVR5Y2VrZytpdUJhQ0ZTNCtjeGdFcElPVGhEaG1mTCtKb3ViclRLS3dGZ2t4SUZEbTRpT1BMK0FvSjYweFxuSGRJMkVxYjVBZ01CQUFFQ2dnRUFFOExuV0R2NUd4VUlZanRRYWZ3NVI3T0VBVElWeTR6RUVaV24zSkZYaU5FUVxuS0pwdUlaK282RFZqR1JiVzVERkxPWnp4dWhZT0JGTXRzeUN5KytPek9MbWFHUmxVQytxV2JmWDFtRGxIbVQyQVxuRk1rZ3BTSjJ0UXIvM1Q4YUZsQlZ2K09nbTY0LzV4eTJJK3p2Yzl2UmdEYTgzOTcxNDg1d2wram5Ka3o4eFp4aVxuY1RzUVpNOHE2OWJWME5ZaWt4M2ZsSkFCTTN0NzJtOGFOc2Y3M3BkVzdNTDdyeSsxUENzeEJnbDY0U3p6VXJDZVxuZFBNUFZ2OWJ6dkV5NWxnNmhIR3htN2lkd1l2Q2l3OXJveEcrdzdGZ0xtbFl4THFUU2E3SGtCYm1PbUZNa1BVK1xudVpZWnRobDVDZXloQmJrUU1ramtXN3BFL01SUTVjcENWUm1UWkpEMUFRS0JnUUQrYjV1ajlIeHJ4T1hHMnV0Vlxudmc2dERoSmpNMGNFMkprcUFPeE1iMjRkdVFQQWdGT08yV2t3WGs1WjVmb3dudUtkczlDSlR1YmtIekx4STNTOFxuL3BSMmxCbWtWN1hJQnpWT1phUDA4eXcvSkV3MHArYTdOOUNUY1d3NHNQaVY2eTVvQ01kOWVyWlY4VmpZb3lSTlxuWXJtL2liL3dxOTY4R0RjM3B4dTVaNnorNlFLQmdRRDdROVZCVE1IdTdKaXJkS0c5NXRLWDZJZmNSR3Y3RTlIVlxucnk0d3JycUpGOUFWNWRjQ1RwdjdnaXZXWStPNDY3QXNJRHZxWVZSUE8xSmJNMXRwTFZLYlZVNFdxS09IZ0lvalxuSTM0WkJxeUp6V0FQQVYyKy9mTE1CZDc0aWJMa0tzTnF2QXoyYkZ4RS9HL1h3Wnh2NnNmSVV3aE1BeVE4aXBtclxuK0RGRHBacjlrUUtCZ0F5TE5oSWtPSW9ibi9SbzBKZGVrbHlueC9KS0VlTkVSbkRTc05PbjNyYnFheXZ2WjY4d1xuT3NaZXIrQXd2Vi91UlYvZkFKWDBaTiswUmcrclh0TCtmaFZHZ2VrZlJlQUJzdmdWZkxyVHprZWlvM3NwRisvOFxuOVhSL2NBVnZmQ0h3QVU2eHVCd1FrN0t5L2wxWDFhOVhBYTlXdkRiQ1VtM1ZoOHRmbXJkT1RESVpBb0dBRzlXYlxuM2l2K245VWQ1SUI3R21wamtlaDBoSFlmOENSMTdsSUZyK2JyU3h5VU5Kak5oTGZvbDZnSDZ5d05vZ0taOVlsc1xubWI1R2RMQ0JveERCWTVsZHVVOXQ0eHl6WU9OZ2Fod1liL1ZKVDhxc2hYMEZRWThvUW1tMEZaeExjUE03eXFzaVxuVkhvVWpwL1lVL0ppdmhNb0pvenNNbDkydUM0eWI5YUN2cGV0MzhFQ2dZRUF1dXk0WDhIQjdyazVLOER3b1BGNlxuMHlWeUptb3BNRWYxVjFRYXZGU1o1MjdLMUYyQ203OTM2RWN5M2Mxb3RWQ2tzQWVTQWpJWW5uNitMWm9YS0tBYlxuU004L1Nhamg4RWNCNU9xMDZjclVISjF3MU5GVTRaSzBMamNpaFl3OHhwcFRMb2dGbm5ESm1VSk11Um4rcnVGR1xuWUprUWFScTJOVkYxSkdsaVUxUjRzQmc9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstN291b2xAZGlhbG9nLTI1ZjM3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExODIxMjk3MTkyOTYyODcxMDkzMyIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstN291b2wlNDBkaWFsb2ctMjVmMzcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K

logging:
  file:
    name: /var/log/springboot/spring.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.epi.epilog: DEBUG